<?//= $job[array_rand($job)] ?>
<?php
$phil = array(
   "A. J. Ayer",
   "Bertrand Russel",
   "Patricia Churchland",
   "W. V. O. Quine",
   "Hillary Putnam",
   "David Chalmers",
   "Noam Chomsky",
   "Daniel Dennet",
   "Alvin Plantinga",
   "Thomas Hobbes",
   "Jean-Paul Sartre",
   "Martin Hediegger",
   "John Searle",
   "Peter Singer",
   "Saul Kripke"
);
$phil_cont = array(
   "Fyodor Dostoyevsky",
   "Paul Tillich",
   "Soren Kierkegaard",
   "Friedrich Nietzsche",
   "Franz Kafka",
   "Hannah Arendt",
   "Karl Barth",
   "Simone de Beauvoir",
   "Edmund Husserl",
   "William James",
   "Albert Camus",
   "Maurice Merleau-Ponty",
   "Jose Ortega",
   "Susan Bordo",
   "Judith Butler",
   "Judith Jarvis Thomson",
   "Angela Davis",
   "Guilles Deleuze",
   "Jacques Derrida",
   "Paulo Freire",
   "Felix Guattari",
   "Jurgen Habermas"
);
$trees = array(
   "Ash",
   "Aspen",
   "Oak",
   "Maple",
   "Hickory",
   "Hemlock",
   "Fir",
   "Elm",
   "Cottonwood",
   "Chestnut",
   "Cherry",
   "Birch",
   "Beech",
   "Basswood",
   "Pine",
   "Spruce",
   "Walnut"
);
$job = array(
   "HVAC",
   "Plumbing",
   "Electric",
   "Cleaning",
   "Painting"
);
$city = array(
   "Columbia",
   "Boston",
   "St. Louis",
   "Kansas City",
   "Palo Alto",
   "New York",
   "Chicago",
   "Providence",
   "Baltimore",
   "Los Angeles",
   "Houston",
   "Philadelphia",
   "Phoenix",
   "San Antonio",
   "San Diego",
   "Oakland",
   "Portland"
);
$state = array(
   "Alabama",
   "Alaska",
   "Arizona",
   "Arkansas",
   "California",
   "Colorado",
   "Connecticut",
   "Delaware",
   //"District Of Columbia",
   "Florida",
   "Georgia",
   "Hawaii",
   "Idaho",
   "Illinois",
   "Indiana",
   "Iowa",
   "Kansas",
   "Kentucky",
   "Louisiana",
   "Maine",
   "Maryland",
   "Massachusetts",
   "Michigan",
   "Minnesota",
   "Mississippi",
   "Missouri",
   "Montana",
   "Nebraska",
   "Nevada",
   "New Hampshire",
   "New Jersey",
   "New Mexico",
   "New York",
   "North Carolina",
   "North Dakota",
   "Ohio",
   "Oklahoma",
   "Oregon",
   "Pennsylvania",
   "Rhode Island",
   "South Carolina",
   "South Dakota",
   "Tennessee",
   "Texas",
   "Utah",
   "Vermont",
   "Virginia",
   "Washington",
   "West Virginia",
   "Wisconsin",
   "Wyoming"
);
$units = array(
   "Joules",
   "Pounds",
   "Boxes",
   "Units",
   "Watts",
   "Newtons",
   "Crates"
);
$project = array(
   "Solar Ice Melt Strip for Roof",
   "Banana Saver",
   "Foam Forts",
   "Air Conditioning Mattress",
   "Power2go",
   "Icebreaker Snow Shovel",
   "Space-War Drone",
   "Pillow Clip",
   "Water Bottle Storage",
   "Modular Growing Wall",
   "Stirring Gloves",
   "Push Hooks",
   "ECO Bin",
   "Beam",
   "Sidwalk Chalk Printer",
);
$imgProfile = array(
   "adellecharles-73.jpg",
   "alagoon-73.jpg",
   "brenton_clarke-73.jpg",
   "chexee-73.jpg",
   "commadelimited-73.jpg",
   "dancounsell-73.jpg"
);
$company = array(
   "SE",
   "Wood Solutions",
   "Pear Crafts",
   "Orange Works",
   "Kale Associates"
);
$food = array(
  "Açai Berries",
  "Apple",
  "Apricot",
  "Avocado",
  "Banana",
  "Bilberry",
  "Blackberry",
  "Blackcurrant",
  "Blueberry",
  "Boysenberry",
  "Cantaloupe",
  "Currant",
  "Cherry",
  "Cherimoya",
  "Cloudberry",
  "Coconut",
  "Cranberry",
  "Damson",
  "Date",
  "Dragonfruit",
  "Durian",
  "Elderberry",
  "Feijoa",
  "Fig",
  "Goji berry",
  "Gooseberry",
  "Grape",
  "Raisin",
  "Grapefruit",
  "Guava",
  "Huckleberry",
  "Jabouticaba",
  "Jackfruit",
  "Jambul",
  "Jujube",
  "Juniper berry",
  "Kiwi fruit",
  "Kumquat",
  "Lemon",
  "Lime",
  "Loquat",
  "Lychee",
  "Mango",
  "Marion berry",
  "Melon",
  "Cantaloupe",
  "Honeydew",
  "Watermelon",
  "Rock melon",
  "Miracle fruit",
  "Mulberry",
  "Nectarine",
  "Olive",
  "Orange",
  "Blood Orange",
  "Clementine",
  "Mandarine",
  "Tangerine",
  "Papaya",
  "Passionfruit",
  "Peach",
  "Pear",
  "Williams pear",
  "Bartlett pear",
  "Persimmon",
  "Physalis",
  "Plum",
  "Pineapple",
  "Pomegranate",
  "Pomelo",
  "Purple Mangosteen",
  "Quince",
  "Raspberry",
  "Salmon berry",
  "Black raspberry",
  "Rambutan",
  "Redcurrant",
  "Salal berry",
  "Satsuma",
  "Star fruit",
  "Strawberry",
  "Tamarillo",
  "Ugli fruit",
  "Artichoke",
  "Arugula",
  "Asparagus",
  "Eggplant",
  "Amaranth",
  "Legumes",
  "Alfalfa sprouts",
  "Azuki beans",
  "Bean sprouts",
  "Black beans",
  "Black-eyed peas",
  "Borlotti bean",
  "Broad beans",
  "Chickpeas",
  "Green beans",
  "Kidney beans",
  "Lentils",
  "Lima beans",
  "Mung beans",
  "Navy beans",
  "Pinto beans",
  "Runner beans",
  "Soy beans",
  "Peas",
  "Snap peas",
  "Bok choy",
  "Broccoli",
  "Brussels sprouts",
  "Cabbage",
  "Calabrese",
  "Cannabis",
  "Carrots",
  "Cauliflower",
  "Celery",
  "Chard",
  "Collard greens",
  "Corn salad",
  "Endive",
  "Frisee",
  "Anise",
  "Basil",
  "Caraway",
  "Cilantro seeds are Coriander",
  "Chamomile",
  "Dill",
  "Fennel",
  "Lavender",
  "Lemon Grass",
  "Marjoram",
  "Oregano",
  "Parsley",
  "Rosemary",
  "Sage",
  "Thyme",
  "Kale",
  "Kohlrabi",
  "Lettuce",
  "Corn",
  "Mushrooms",
  "Mustard greens",
  "Nettles",
  "New Zealand spinach",
  "Okra",
  "Onion family",
  "Chives",
  "Garlic",
  "Leek Allium porrum",
  "Onion",
  "Shallot",
  "Green onion",
  "Parsley",
  "Green pepper",
  "Red pepper",
  "Jalapeno",
  "Habanero",
  "Paprika",
  "Tabasco pepper",
  "Cayenne pepper",
  "Radicchio",
  "Rhubarb",
  "Beet",
  "Carrot",
  "Celeriac",
  "Daikon",
  "Ginger",
  "Parsnip",
  "Rutabaga",
  "Turnip",
  "Radish",
  "Rutabaga",
  "Turnip",
  "Wasabi",
  "Horseradish",
  "White radish",
  "Skirret",
  "Spinach",
  "Topinambur",
  "Acorn squash",
  "Butternut squash",
  "Banana squash",
  "Zucchini",
  "Cucumber",
  "Delicata",
  "Gem squash",
  "Hubbard squash",
  "Squash",
  "Patty pans",
  "Pumpkin",
  "Spaghetti squash",
  "Tat soi",
  "Tomato",
  "Tubers",
  "Jicama",
  "Jerusalem artichoke",
  "Potato",
  "Sweet potato",
  "Taro",
  "Yam",
  "Water chestnut",
  "Watercress",
  "Zucchini"
);
?>
